CLASS cx_apj_rt_content DEFINITION PUBLIC INHERITING FROM cx_apj_rt CREATE PUBLIC.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS cx_apj_rt_content IMPLEMENTATION.
ENDCLASS.
